name: Build & Push Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          docker build \
            -t ghcr.io/chhaviii0905/inventorymanagementsystemapis:latest \
            .
          docker push ghcr.io/chhaviii0905/inventorymanagementsystemapis:latest
